DROP TABLE Utilisateur CASCADE CONSTRAINTS
/
DROP TABLE Employé CASCADE CONSTRAINTS
/
DROP TABLE Membre CASCADE CONSTRAINTS
/
DROP TABLE PrêtEnCours CASCADE CONSTRAINTS
/
DROP TABLE PrêtArchivé CASCADE CONSTRAINTS
/
DROP TABLE MembreGénéral CASCADE CONSTRAINTS
/
DROP TABLE Exemplaire CASCADE CONSTRAINTS
/
DROP TABLE Livre CASCADE CONSTRAINTS
/
DROP TABLE Auteur CASCADE CONSTRAINTS
/
DROP TABLE AuteurLivre CASCADE CONSTRAINTS
/
DROP TABLE Catégorie CASCADE CONSTRAINTS
/
DROP TABLE Editeur CASCADE CONSTRAINTS
/
DROP SEQUENCE SequenceNoPrêtArchivé
/

